export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as Layout } from "./Layout";
export { default as Main } from "./Main";
export { default as HowItWorks } from "./HowItWorks";
export { default as CallToAction } from "./CallToAction";
export { default as SwiperHero } from "./SwiperHero";
export { default as DestinationInfo } from "./DestinationInfo";
export { default as TabsSection } from "./TabsSection";
